WIP: Issue 151 Include :_module-type: variable into the template
redhat-documentation/modular-docs pull request #164
Opened 2021-03-31 14:46 UTC by emmurphy1

[ Issue 151 Include :_module-type: variable into the template](https://github.com/redhat-documentation/modular-docs/issues/151)

2021-04-05 10:25 UTC, rolfedh approved these changes

2021-04-06 13:17 UTC, fbolton approved these changes
LGTM

2021-04-06 14:38 UTC, mikemckiernan commented
The change looks good, so formally, that is my approval.

That said:
- The module type is not customer-facing, or at least not compelling to make customer-facing.  Ideally, we would not add this attribute to the docs.
- If the change *must* be made, I'd prefer that we amend the code to accept lowercase for the type.

I have the second bullet working in a playpen, but maven is misbehaving _for me_, so I have not submitted a PR. The gist is to change the foll line from "attValue.toString()" to "attValue.toString.toUpperCase()".
https://github.com/redhataccess/pantheon/blob/master/pantheon-bundle/src/main/java/com/redhat/pantheon/asciidoctor/extension/MetadataExtractorTreeProcessor.java#L150
Do we want to hold off for a code change?

2021-04-07 09:52 UTC, rkratky requested changes

2021-04-07 09:52 UTC, rkratky commented on modular-docs-manual/files/TEMPLATE_CONCEPT_concept-explanation.adoc
> +Add `:_module-type: CONCEPT` before the module ID.
This being a comment (i.e. it won't be rendered anywhere), I don't see why the code should be enclosed in backticks.

```suggestion
Add the following attribute before the module ID:
:_module-type: CONCEPT
```

2021-04-07 09:52 UTC, rkratky commented on modular-docs-manual/files/TEMPLATE_PROCEDURE_doing-one-procedure.adoc
> +Add `:_module-type: PROCEDURE` before the module ID.
```suggestion
Add the following attribute before the module ID:
:_module-type: PROCEDURE
```

2021-04-07 09:52 UTC, rkratky commented on modular-docs-manual/files/TEMPLATE_REFERENCE_reference-material.adoc
> +Add `:_module-type: REFERENCE` before the module ID.
```suggestion
Add the following attribute before the module ID:
:_module-type: REFERENCE
```

2021-04-07 09:55 UTC, rkratky commented
@mikemckiernan,

> formally, that is my approval

I suggest you use the GH "Review" functionality to record your approval.

> I'd prefer that we amend the code to accept lowercase for the type

Agree, but that's a Pv2 matter (and as such, it should have no bearing on what happens in this repo).

2021-04-07 09:57 UTC, yzimmerm approved these changes

2021-04-07 11:06 UTC, mikemckiernan approved these changes
/lgtm

Maven behaved for me yesterday, so I submitted a PR to accept lowercase.  Dunno if anyone else cares or cares to wait.

https://github.com/redhataccess/pantheon/pull/562

2021-04-07 14:21 UTC, sterobin approved these changes

2021-04-14 12:07 UTC, Preeticp approved these changes
LGTM

2021-05-03 18:04 UTC, merged